In [2]:
! pip install numpy

In [3]:
 pip install pandas 

In [2]:
import numpy as np 
A = np.array ([10,20,30,40,50])
B = np.array ([5,4,3,2,1])
#perform operations 
print ( A + B )
print ( A - B )
print ( A * B ) 
print ( A / B )
#Apply NumPy functions 
print ( A.max() )
print ( A.min() )
print ( A.mean() )
#dot product
C = A*B 
print ( C.sum() )
Reshaped_A= A.reshape(5,1)
print ( Reshaped_A)






[15 24 33 42 51]
[ 5 16 27 38 49]
[50 80 90 80 50]
[ 2.  5. 10. 20. 50.]
50
10
30.0
350
[[10]
 [20]
 [30]
 [40]
 [50]]
